# Generated by Django 6.0.1 on 2026-03-07 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0009_consultantserviceprofile_average_rating_and_more'),
        ('service_orders', '0002_orderitem_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='selected_consultant',
            field=models.ForeignKey(blank=True, help_text='Consultant chosen by client (manual) or system (auto)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items_selected', to='consultants.consultantserviceprofile'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='selection_mode',
            field=models.CharField(choices=[('auto', 'Auto-Assigned'), ('manual', 'Manually Chosen')], default='auto', max_length=10),
        ),
    ]
