# Generated by Django 6.0.1 on 2026-03-26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0017_topic_service'),
        ('service_orders', '0003_add_consultant_selection_to_orderitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='from_booking',
            field=models.ForeignKey(
                blank=True,
                help_text='Set when this order was initiated during a live consultation call',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='additional_service_orders',
                to='consultations.consultationbooking',
            ),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='initiated_by',
            field=models.ForeignKey(
                blank=True,
                help_text='Consultant who requested this additional payment',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='initiated_additional_orders',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='is_additional',
            field=models.BooleanField(
                default=False,
                help_text='True if this order was initiated by a consultant during a live consultation',
            ),
        ),
    ]
