# Generated by Django 6.0.1 on 2026-03-27 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0003_add_consultant_selection_to_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('description', models.CharField(blank=True, help_text="Internal note, e.g. 'Diwali 2026 promo'", max_length=255)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage (e.g. 10 for 10%) or fixed amount in INR', max_digits=10)),
                ('min_purchase_amount', models.DecimalField(decimal_places=2, default=0, help_text='Minimum cart total required to use this coupon', max_digits=10)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Cap on discount for percentage coupons (optional)', max_digits=10, null=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('usage_limit', models.PositiveIntegerField(default=1, help_text='Total times this coupon can be redeemed')),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Absolute discount applied', max_digits=10),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cart total before coupon discount', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='service_orders.coupon'),
        ),
    ]
