# Generated by Django 6.0.1 on 2026-03-27 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0004_coupon_serviceorder_discount_amount_and_more'),
        ('service_orders', '0004_serviceorder_additional_fields'),
    ]

    operations = [
    ]
