# Generated by Django 6.0.1 on 2026-03-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0005_coupon_and_serviceorder_coupon_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='usage_limit',
            field=models.PositiveIntegerField(default=0, help_text='0 = unlimited'),
        ),
    ]
