# Generated by Django 6.0.1 on 2026-03-28 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0006_alter_coupon_id_alter_coupon_usage_limit'),
        ('service_orders', '0006_alter_coupon_options_alter_coupon_code_and_more'),
    ]

    operations = [
    ]
