# Generated by Django 6.0.1 on 2026-03-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_orders', '0007_merge_20260328_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Catalog/base price before any consultant override', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price_update_reason',
            field=models.CharField(blank=True, default='', help_text='Mandatory reason when consultant edits the catalog price', max_length=255),
        ),
    ]
