# Generated by Django 6.0.1 on 2026-02-25 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultantApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('google_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('middle_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=20)),
                ('practice_type', models.CharField(blank=True, choices=[('Individual', 'Individual')], max_length=50, null=True)),
                ('qualification', models.CharField(blank=True, max_length=255)),
                ('experience_years', models.IntegerField(default=0)),
                ('certifications', models.TextField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('has_accepted_declaration', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Assessment'), ('REVIEW', 'Under Admin Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('test_score', models.IntegerField(blank=True, null=True)),
                ('test_passed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Consultant Application',
                'verbose_name_plural': 'Consultant Applications',
                'db_table': 'consultant_applications',
            },
        ),
        migrations.CreateModel(
            name='SandboxToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sandbox Token',
                'verbose_name_plural': 'Sandbox Tokens',
                'db_table': 'application_sandbox_tokens',
            },
        ),
        migrations.CreateModel(
            name='TestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'db_table': 'application_assessment_testtype',
            },
        ),
        migrations.CreateModel(
            name='AuthConsultantDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('Qualification', 'Qualification Degree'), ('Certificate', 'Certificate'), ('bachelors_degree', "Bachelor's Degree"), ('masters_degree', "Master's Degree"), ('certificate', 'Certificate (Additional)')], max_length=50)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='consultant_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='consultant_onboarding.consultantapplication')),
            ],
            options={
                'verbose_name': 'Auth Consultant Document',
                'verbose_name_plural': 'Auth Consultant Documents',
                'db_table': 'application_consultant_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsultantDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_type', models.CharField(max_length=100)),
                ('document_type', models.CharField(max_length=100)),
                ('file_path', models.CharField(max_length=500)),
                ('verification_status', models.CharField(blank=True, max_length=50, null=True)),
                ('gemini_raw_response', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultant_documents', to='consultant_onboarding.consultantapplication')),
            ],
            options={
                'db_table': 'application_consultant_documents_consultantdocument',
            },
        ),
        migrations.CreateModel(
            name='FaceVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_image_path', models.CharField(max_length=255)),
                ('live_image_path', models.CharField(blank=True, default='', max_length=255)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('is_match', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_verifications', to='consultant_onboarding.consultantapplication')),
            ],
            options={
                'db_table': 'application_face_verifications',
                'ordering': ['-verified_at'],
            },
        ),
        migrations.CreateModel(
            name='IdentityDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document_type', models.CharField(blank=True, help_text='Type of document identified by Gemini (e.g., Aadhaar, PAN)', max_length=100, null=True)),
                ('verification_status', models.CharField(blank=True, help_text='Verification status from Gemini (e.g., Verified, Invalid)', max_length=50, null=True)),
                ('gemini_raw_response', models.TextField(blank=True, help_text='Raw JSON response from Gemini', null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_documents', to='consultant_onboarding.consultantapplication')),
            ],
            options={
                'db_table': 'application_identity_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PANVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_full_name', models.CharField(blank=True, max_length=255)),
                ('verified_dob', models.DateField(blank=True, null=True)),
                ('full_name_match', models.BooleanField(default=False)),
                ('dob_match', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=20)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pan_verification', to='consultant_onboarding.consultantapplication')),
            ],
            options={
                'verbose_name': 'PAN Verification',
                'verbose_name_plural': 'PAN Verifications',
                'db_table': 'application_pan_verifications',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_domains', models.JSONField(default=list)),
                ('question_set', models.JSONField(default=list)),
                ('video_question_set', models.JSONField(default=list)),
                ('score', models.FloatField(default=0.0)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('flagged', 'Flagged')], default='ongoing', max_length=20)),
                ('violation_count', models.IntegerField(default=0)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_sessions', to='consultant_onboarding.consultantapplication')),
                ('test_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultant_onboarding.testtype')),
            ],
            options={
                'db_table': 'application_assessment_usersession',
            },
        ),
        migrations.CreateModel(
            name='ProctoringSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_violation', models.BooleanField(default=False)),
                ('violation_reason', models.TextField(blank=True, null=True)),
                ('face_count', models.IntegerField(default=0)),
                ('match_score', models.FloatField(default=0.0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_snapshots', to='consultant_onboarding.usersession')),
            ],
            options={
                'db_table': 'application_assessment_proctoringsnapshot',
            },
        ),
        migrations.CreateModel(
            name='VideoQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('test_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_questions', to='consultant_onboarding.testtype')),
            ],
            options={
                'db_table': 'application_assessment_videoquestion',
            },
        ),
        migrations.CreateModel(
            name='VideoResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_identifier', models.CharField(default='unknown', max_length=255)),
                ('video_file', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ai_transcript', models.TextField(blank=True, null=True)),
                ('ai_score', models.IntegerField(blank=True, null=True)),
                ('ai_feedback', models.JSONField(blank=True, null=True)),
                ('ai_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_responses', to='consultant_onboarding.usersession')),
            ],
            options={
                'db_table': 'application_assessment_videoresponse',
            },
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='consultant_onboarding.usersession')),
            ],
            options={
                'db_table': 'application_assessment_violation',
            },
        ),
    ]
