# Generated by Django 6.0.1 on 2026-02-25 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant_onboarding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultantCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='consultant_onboarding.consultantapplication')),
            ],
            options={
                'verbose_name': 'Consultant Credential',
                'verbose_name_plural': 'Consultant Credentials',
                'db_table': 'application_consultant_credentials',
            },
        ),
    ]
