# Generated by Django 6.0.1 on 2026-02-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant_onboarding', '0002_consultantcredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='cam_violation_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersession',
            name='is_disqualified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersession',
            name='tab_switch_count',
            field=models.IntegerField(default=0),
        ),
    ]
