# Generated by Django 6.0.1 on 2026-03-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultant_onboarding', '0003_usersession_cam_violation_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='cam_violation_count',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='is_disqualified',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='tab_switch_count',
        ),
        migrations.AddField(
            model_name='proctoringsnapshot',
            name='audio_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proctoringsnapshot',
            name='gaze_violation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proctoringsnapshot',
            name='label_detection_results',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='proctoringsnapshot',
            name='mouth_state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='proctoringsnapshot',
            name='pose_pitch',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proctoringsnapshot',
            name='pose_roll',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proctoringsnapshot',
            name='pose_yaw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proctoringsnapshot',
            name='rule_outcomes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='proctoringsnapshot',
            name='snapshot_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='violation_counters',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddConstraint(
            model_name='proctoringsnapshot',
            constraint=models.UniqueConstraint(fields=('session', 'snapshot_id'), name='uniq_snapshot_per_session_id'),
        ),
    ]
