# Generated by Django 6.0.1 on 2026-01-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_auth', '0003_allow_null_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='gst_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='gstin',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
