# Generated by Django 6.0.1 on 2026-01-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_auth', '0003_allow_null_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantprofile',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=10),
        ),
    ]
