# Generated by Django 6.0.1 on 2026-01-31 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_auth', '0004_clientprofile_gst_username_clientprofile_gstin'),
        ('core_auth', '0004_consultantprofile_consultation_fee'),
    ]

    operations = [
    ]
