# Generated by Django 6.0.1 on 2026-02-12 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_auth', '0005_merge_20260131_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultantprofile',
            name='services',
        ),
    ]
