# Generated by Django 6.0.1 on 2026-03-09 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_auth', '0006_remove_consultantprofile_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('inquiry_type', models.CharField(choices=[('Feedback', 'Feedback'), ('Sales', 'Sales'), ('Support', 'Support'), ('Partnership', 'Partnership'), ('Other', 'Other')], default='Other', max_length=50)),
                ('message', models.TextField(max_length=2000)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
