# Generated by Django 6.0.1 on 2026-03-21 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_auth', '0008_magiclinktoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='assigned_consultant',
        ),
    ]
