# Generated by Django 6.0.1 on 2026-03-17 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_auth', '0008_magiclinktoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='parent_account',
            field=models.ForeignKey(blank=True, help_text='If set, this user is a sub-account managed by the parent_account.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_accounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
