# Generated by Django 6.0.1 on 2026-03-21 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_auth', '0009_remove_clientprofile_assigned_consultant'),
        ('core_auth', '0009_user_parent_account'),
    ]

    operations = [
    ]
