# Generated by Django 6.0.1 on 2026-02-07 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('document_upload', 'Document Uploaded'), ('document_verify', 'Document Verified'), ('document_reject', 'Document Rejected'), ('service_new', 'New Service Request'), ('service_status', 'Service Status Changed'), ('service_complete', 'Service Completed'), ('call_made', 'Call Made'), ('call_received', 'Call Received'), ('system_reminder', 'System Reminder'), ('profile_update', 'Profile Updated')], max_length=30)),
                ('title', models.CharField(help_text='Brief activity description', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description', null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional activity data (duration, status, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(help_text='User who performed this activity', on_delete=django.db.models.deletion.CASCADE, related_name='activities_performed', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('target_user', models.ForeignKey(help_text='User this activity is about', on_delete=django.db.models.deletion.CASCADE, related_name='activities_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'db_table': 'activity_timeline',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor', '-created_at'], name='activity_ti_actor_i_458442_idx'), models.Index(fields=['target_user', '-created_at'], name='activity_ti_target__85d52e_idx'), models.Index(fields=['activity_type', '-created_at'], name='activity_ti_activit_3e40f5_idx'), models.Index(fields=['content_type', 'object_id'], name='activity_ti_content_8ce44f_idx')],
            },
        ),
    ]
