# Generated by Django 6.0.1 on 2026-03-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_timeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(
                choices=[
                    ('document_upload', 'Document Uploaded'),
                    ('document_verify', 'Document Verified'),
                    ('document_reject', 'Document Rejected'),
                    ('service_new', 'New Service Request'),
                    ('service_status', 'Service Status Changed'),
                    ('service_complete', 'Service Completed'),
                    ('additional_payment_requested', 'Additional Payment Requested'),
                    ('additional_payment_paid', 'Additional Payment Completed'),
                    ('additional_service_added', 'Additional Service Added'),
                    ('call_made', 'Call Made'),
                    ('call_received', 'Call Received'),
                    ('system_reminder', 'System Reminder'),
                    ('profile_update', 'Profile Updated'),
                ],
                max_length=30,
            ),
        ),
    ]
