questions = [
    {
        "id": 1,
        "question": "Which form is commonly used for a PAN application by an Indian individual or entity?",
        "options": {"A": "Form 49A", "B": "Form 49AA", "C": "Form 26QB", "D": "Form 10A"},
        "answer": "A",
    },
    {
        "id": 2,
        "question": "Which form is generally used for a PAN application by a foreign citizen or foreign entity?",
        "options": {"A": "Form 49A", "B": "Form 49AA", "C": "Form 49B", "D": "SPICe+"},
        "answer": "B",
    },
    {
        "id": 3,
        "question": "Which form is generally used to apply for TAN registration?",
        "options": {"A": "Form 49A", "B": "Form 49AA", "C": "Form 49B", "D": "DIR-3"},
        "answer": "C",
    },
    {
        "id": 4,
        "question": "TAN is primarily required for which purpose?",
        "options": {"A": "Filing GST annual return", "B": "Deducting or collecting tax at source", "C": "Opening a current account", "D": "Registering an LLP"},
        "answer": "B",
    },
    {
        "id": 5,
        "question": "If PAN is not linked with Aadhaar where linkage is mandatory, PAN may become:",
        "options": {"A": "Optional", "B": "Inoperative", "C": "Converted into TAN", "D": "A GSTIN"},
        "answer": "B",
    },
    {
        "id": 6,
        "question": "Aadhaar validation in tax workflows is most commonly used to:",
        "options": {"A": "Replace DSC in all filings", "B": "Confirm identity details and support linked compliance", "C": "Issue IEC automatically", "D": "Register a trust deed"},
        "answer": "B",
    },
    {
        "id": 7,
        "question": "Udyam registration is associated with which category of businesses?",
        "options": {"A": "Only listed companies", "B": "MSMEs", "C": "Only foreign companies", "D": "Only charitable trusts"},
        "answer": "B",
    },
    {
        "id": 8,
        "question": "For a proprietorship MSME registration, whose Aadhaar is usually used?",
        "options": {"A": "Any employee", "B": "The proprietor", "C": "The auditor", "D": "The GST officer"},
        "answer": "B",
    },
    {
        "id": 9,
        "question": "IEC is issued by which authority in India?",
        "options": {"A": "Income Tax Department", "B": "DGFT", "C": "MCA", "D": "SEBI"},
        "answer": "B",
    },
    {
        "id": 10,
        "question": "Import Export Code (IEC) is generally required for:",
        "options": {"A": "Import or export of goods or services", "B": "Only domestic GST return filing", "C": "Applying for Aadhaar", "D": "Only TDS quarterly returns"},
        "answer": "A",
    },
    {
        "id": 11,
        "question": "Which document is fundamental for partnership firm registration?",
        "options": {"A": "GST audit report", "B": "Partnership deed", "C": "Share certificate", "D": "Bill of entry"},
        "answer": "B",
    },
    {
        "id": 12,
        "question": "An unregistered partnership firm commonly faces difficulty in:",
        "options": {"A": "Opening a bank account", "B": "Enforcing contractual claims in court", "C": "Obtaining PAN", "D": "Maintaining books"},
        "answer": "B",
    },
    {
        "id": 13,
        "question": "An LLP in India is governed primarily by which law?",
        "options": {"A": "Income Tax Act", "B": "LLP Act, 2008", "C": "Indian Trusts Act", "D": "GST Act"},
        "answer": "B",
    },
    {
        "id": 14,
        "question": "How many designated partners are generally required for an LLP?",
        "options": {"A": "At least 1", "B": "At least 2", "C": "At least 3", "D": "At least 5"},
        "answer": "B",
    },
    {
        "id": 15,
        "question": "A private limited company generally requires at least how many directors?",
        "options": {"A": "1", "B": "2", "C": "3", "D": "5"},
        "answer": "B",
    },
    {
        "id": 16,
        "question": "Which MCA filing route is commonly used for company incorporation in India?",
        "options": {"A": "ASMT-10", "B": "SPICe+", "C": "Form 49B", "D": "Form 10AB"},
        "answer": "B",
    },
    {
        "id": 17,
        "question": "Startup India recognition is associated with which authority framework?",
        "options": {"A": "DPIIT recognition", "B": "SEBI merchant banking", "C": "CBDT prosecution", "D": "RBI compounding"},
        "answer": "A",
    },
    {
        "id": 18,
        "question": "Startup India recognition is generally relevant for:",
        "options": {"A": "Import duty payment only", "B": "Eligible startup benefits and recognition", "C": "Replacing PAN", "D": "Trust deed registration"},
        "answer": "B",
    },
    {
        "id": 19,
        "question": "Trust formation usually starts with drafting which core document?",
        "options": {"A": "Memorandum of Association", "B": "Trust deed", "C": "Bill of lading", "D": "Partnership resolution"},
        "answer": "B",
    },
    {
        "id": 20,
        "question": "For trusts involving immovable property, registration of the trust deed is commonly done before:",
        "options": {"A": "Registrar or Sub-Registrar", "B": "GST officer", "C": "SEBI", "D": "DGFT"},
        "answer": "A",
    },
    {
        "id": 21,
        "question": "12A registration is primarily sought to obtain:",
        "options": {"A": "Import benefits", "B": "Income-tax exemption for eligible charitable or religious entities", "C": "TAN allotment", "D": "GST cancellation"},
        "answer": "B",
    },
    {
        "id": 22,
        "question": "Initial application for 12A or 80G registration is commonly made in which form set?",
        "options": {"A": "Form 49A/49AA", "B": "Form 10A or 10AB", "C": "GSTR-10", "D": "Form 16A"},
        "answer": "B",
    },
    {
        "id": 23,
        "question": "80G registration is mainly important because it helps:",
        "options": {"A": "Convert a trust into a company", "B": "Donors claim eligible deduction on donations", "C": "Obtain IEC automatically", "D": "Avoid PAN altogether"},
        "answer": "B",
    },
    {
        "id": 24,
        "question": "Which statement best matches the relationship between 12A and 80G?",
        "options": {"A": "They are unrelated to charitable entities", "B": "12A focuses on entity tax exemption and 80G focuses on donor deduction benefit", "C": "80G replaces PAN", "D": "12A is only for LLPs"},
        "answer": "B",
    },
    {
        "id": 25,
        "question": "A DSC is most commonly used for:",
        "options": {"A": "Digitally signing statutory filings and forms", "B": "Replacing a passport", "C": "Opening IEC without PAN", "D": "Computing capital gains"},
        "answer": "A",
    },
    {
        "id": 26,
        "question": "For MCA and other secure filing workflows today, which DSC class is generally used?",
        "options": {"A": "Class 1", "B": "Class 2", "C": "Class 3", "D": "Class 4"},
        "answer": "C",
    },
    {
        "id": 27,
        "question": "In an HUF PAN application, who usually signs on behalf of the HUF?",
        "options": {"A": "Any coparcener", "B": "The karta", "C": "The auditor", "D": "The bank manager"},
        "answer": "B",
    },
    {
        "id": 28,
        "question": "An HUF PAN application commonly requires which supporting concept?",
        "options": {"A": "A declaration or deed identifying the HUF and karta", "B": "IEC certificate", "C": "LLP agreement", "D": "GST annual return"},
        "answer": "A",
    },
    {
        "id": 29,
        "question": "For an NRI PAN application, which document is commonly accepted as identity proof?",
        "options": {"A": "GST registration certificate", "B": "Passport", "C": "Certificate of incorporation", "D": "Trust deed"},
        "answer": "B",
    },
    {
        "id": 30,
        "question": "NRI PAN applications often require foreign address proof that is:",
        "options": {"A": "Always oral", "B": "Properly supported and, where required, attested", "C": "Not needed", "D": "Filed only with MCA"},
        "answer": "B",
    },
    {
        "id": 31,
        "question": "Foreign entity PAN registration in India is commonly linked with which PAN form?",
        "options": {"A": "Form 49A", "B": "Form 49AA", "C": "Form 49B", "D": "SPICe+"},
        "answer": "B",
    },
    {
        "id": 32,
        "question": "Documents issued outside India for a foreign entity registration are commonly expected to be:",
        "options": {"A": "Unsigned", "B": "Apostilled or consularized where applicable", "C": "Self-written only", "D": "Submitted without translation ever"},
        "answer": "B",
    },
]
