# Generated by Django 6.0.1 on 2026-02-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exotel_calls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calllog',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calllog',
            name='from_number',
            field=models.CharField(blank=True, help_text='Masked for privacy', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='calllog',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes from the consultant', null=True),
        ),
        migrations.AddField(
            model_name='calllog',
            name='outcome',
            field=models.CharField(blank=True, choices=[('connected', 'Connected - Successful'), ('voicemail', 'Left Voicemail'), ('no_answer', 'No Answer'), ('busy', 'Line Busy'), ('callback', 'Callback Requested'), ('interested', 'Interested - Follow Up'), ('not_interested', 'Not Interested'), ('wrong_number', 'Wrong Number'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='calllog',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Call cost', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='calllog',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calllog',
            name='to_number',
            field=models.CharField(blank=True, help_text='Masked for privacy', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='recording_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
