# Generated by Django 6.0.1 on 2026-02-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exotel_calls', '0002_calllog_end_time_calllog_follow_up_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calllog',
            name='from_number',
            field=models.CharField(blank=True, help_text='Caller phone number', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='to_number',
            field=models.CharField(blank=True, help_text='Callee phone number', max_length=20, null=True),
        ),
    ]
