# Generated by Django 6.0.1 on 2026-03-12 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0016_consultationbooking_reschedule_count_and_more'),
        ('exotel_calls', '0003_alter_calllog_from_number_alter_calllog_to_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], db_index=True, default='pending', max_length=20)),
                ('exotel_sid', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_calls', to='consultations.consultationbooking')),
            ],
            options={
                'ordering': ['run_at'],
                'indexes': [models.Index(fields=['status', 'run_at'], name='exotel_call_status_311903_idx')],
            },
        ),
    ]
