# Generated by Django 6.0.1 on 2026-03-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='delivery_channel',
            field=models.CharField(choices=[('dashboard', 'Dashboard Only'), ('wa_pending', 'WhatsApp Pending'), ('wa_text', 'WhatsApp Text Sent'), ('wa_template', 'WhatsApp Template Fallback'), ('wa_failed', 'WhatsApp Failed')], default='dashboard', help_text='How this message was delivered to the recipient', max_length=20),
        ),
    ]
