# Generated by Django 6.0.1 on 2026-02-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientservicerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Assignment'), ('assigned', 'Consultant Assigned'), ('doc_pending', 'Documents Pending'), ('under_review', 'Under Review'), ('wip', 'Work In Progress'), ('under_query', 'Clarification Needed'), ('final_review', 'Final Review'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
