# Generated by Django 6.0.1 on 2026-02-13 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0003_alter_clientservicerequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientservicerequest',
            name='revision_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
