# Generated by Django 6.0.1 on 2026-02-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0004_clientservicerequest_revision_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultantserviceprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='consultantserviceprofile',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='consultantserviceprofile',
            name='phone',
        ),
        migrations.AddField(
            model_name='consultantserviceprofile',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='consultantserviceprofile',
            name='last_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultantserviceprofile',
            name='experience_years',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='consultantserviceprofile',
            name='qualification',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
