# Generated by Django 6.0.1 on 2026-02-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0004_clientservicerequest_revision_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantserviceprofile',
            name='last_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
