# Generated by Django 6.0.1 on 2026-02-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0007_migrate_consultation_fee_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantserviceprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Short professional biography displayed to clients'),
        ),
    ]
