# Generated by Django 6.0.1 on 2026-03-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0009_consultantserviceprofile_average_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientservicerequest',
            name='cancellation_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientservicerequest',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
