# Generated by Django 6.0.1 on 2026-03-27 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0010_cancellation_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientservicerequest',
            name='service',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='consultants.service',
            ),
        ),
    ]
