# Generated by Django 6.0.1 on 2026-03-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0011_alter_clientservicerequest_service_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultantserviceprofile',
            name='gstin',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='consultantserviceprofile',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
