# Generated by Django 6.0.1 on 2026-01-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_consultationbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationbooking',
            name='notes',
            field=models.TextField(blank=True, help_text="Client's query or meeting details"),
        ),
    ]
