# Generated by Django 6.0.1 on 2026-01-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_consultationbooking_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationbooking',
            name='confirmation_sent',
            field=models.BooleanField(default=False, help_text='Whether confirmation email was sent'),
        ),
        migrations.AddField(
            model_name='consultationbooking',
            name='reminder_sent',
            field=models.BooleanField(default=False, help_text='Whether 24-hour reminder was sent'),
        ),
    ]
