# Generated by Django 6.0.1 on 2026-01-27 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_consultationbooking_confirmation_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationbooking',
            name='recording_id',
            field=models.CharField(blank=True, help_text='Zego TaskID for recording', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='consultationbooking',
            name='recording_url',
            field=models.URLField(blank=True, help_text='Final S3 recording URL', max_length=500, null=True),
        ),
    ]
