# Generated by Django 6.0.1 on 2026-01-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0005_consultationbooking_recording_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationbooking',
            name='meeting_link',
            field=models.URLField(blank=True, help_text='Google Meet meeting link', max_length=500, null=True),
        ),
    ]
