# Generated by Django 6.0.1 on 2026-01-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0006_consultationbooking_meeting_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationbooking',
            name='bot_recorded',
            field=models.BooleanField(default=False, help_text='Whether the recording was successfully started'),
        ),
        migrations.AddField(
            model_name='consultationbooking',
            name='bot_triggered',
            field=models.BooleanField(default=False, help_text='Whether the recording bot was launched'),
        ),
        migrations.AlterField(
            model_name='consultationbooking',
            name='recording_id',
            field=models.CharField(blank=True, help_text='TaskID for recording', max_length=100, null=True),
        ),
    ]
