# Generated by Django 6.0.1 on 2026-01-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0008_consultationbooking_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='price',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
        ),
    ]
