# Generated by Django 6.0.1 on 2026-01-30 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0009_topic_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='price',
        ),
    ]
