# Generated by Django 6.0.1 on 2026-02-12 12:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0010_remove_topic_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='consultants',
            field=models.ManyToManyField(blank=True, related_name='topics', to=settings.AUTH_USER_MODEL),
        ),
    ]
