# Generated by Django 6.0.1 on 2026-02-12 12:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0011_topic_consultants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='consultants',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'CONSULTANT'}, related_name='topics', to=settings.AUTH_USER_MODEL),
        ),
    ]
