# Generated by Django 6.0.1 on 2026-02-16 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0006_remove_consultantserviceprofile_email_and_more'),
        ('consultations', '0012_alter_topic_consultants'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Link to ServiceCategory for auto-sync of consultants', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to='consultants.servicecategory'),
        ),
    ]
