# Generated by Django 6.0.1 on 2026-02-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0013_topic_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationbooking',
            name='attachment',
            field=models.FileField(blank=True, help_text='User uploaded document', null=True, upload_to='consultation_attachments/'),
        ),
    ]
