# Generated by Django 6.0.1 on 2026-02-20 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0014_consultationbooking_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationbooking',
            name='attachment',
        ),
        migrations.CreateModel(
            name='ConsultationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='consultation_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='consultations.consultationbooking')),
            ],
        ),
    ]
