# Generated by Django 6.0.1 on 2026-02-21 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0015_remove_consultationbooking_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationbooking',
            name='reschedule_count',
            field=models.IntegerField(default=0, help_text='Number of times this booking has been rescheduled'),
        ),
        migrations.AddField(
            model_name='consultationbooking',
            name='reschedule_history',
            field=models.JSONField(blank=True, default=list, help_text='History of previous dates and times'),
        ),
    ]
