# Generated by Django 6.0.1 on 2026-03-13 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0009_consultantserviceprofile_average_rating_and_more'),
        ('consultations', '0016_consultationbooking_reschedule_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='service',
            field=models.OneToOneField(blank=True, help_text='Direct link to a service for auto-sync of expertise', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultation_topic', to='consultants.service'),
        ),
    ]
