# Generated by Django 6.0 on 2026-01-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GSTReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('GSTR1_VS_3B', 'GSTR-1 vs GSTR-3B'), ('GSTR1_VS_BOOK', 'GSTR-1 vs Books'), ('GSTR3B_VS_BOOK', 'GSTR-3B vs Books'), ('GSTR2B_VS_BOOK', 'GSTR-2B vs Books')], db_index=True, max_length=50)),
                ('username', models.CharField(max_length=255)),
                ('gstin', models.CharField(db_index=True, max_length=15)),
                ('reco_type', models.CharField(blank=True, max_length=20, null=True)),
                ('year', models.IntegerField(db_index=True)),
                ('month', models.IntegerField(blank=True, db_index=True, null=True)),
                ('quarter', models.CharField(blank=True, db_index=True, max_length=5, null=True)),
                ('report_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'GST Unified Report',
                'verbose_name_plural': 'GST Unified Reports',
                'db_table': 'gst_unified_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
