# Generated by Django 6.0 on 2026-01-20 08:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst_reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SandboxAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(help_text='Sandbox API access token')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Token expiry time (24 hours from creation)')),
            ],
            options={
                'db_table': 'sandbox_access_token',
            },
        ),
        migrations.CreateModel(
            name='CachedGSTResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gstin', models.CharField(db_index=True, max_length=15)),
                ('return_type', models.CharField(db_index=True, help_text='e.g., GSTR1, GSTR3B, GSTR2B', max_length=20)),
                ('section', models.CharField(blank=True, default='', help_text='e.g., b2b, summary, auto-liability-calc', max_length=50)),
                ('year', models.IntegerField(db_index=True)),
                ('month', models.IntegerField(db_index=True)),
                ('raw_json', models.JSONField(help_text='Raw API response from Sandbox')),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cached_gst_responses',
                'ordering': ['-fetched_at'],
                'indexes': [models.Index(fields=['gstin', 'return_type', 'year', 'month'], name='cached_gst__gstin_8e8e55_idx')],
                'unique_together': {('gstin', 'return_type', 'section', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='UnifiedGSTSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('gstin', models.CharField(max_length=15)),
                ('access_token', models.TextField(blank=True, help_text='Initial sandbox access token', null=True)),
                ('taxpayer_token', models.TextField(blank=True, help_text='Token after OTP verification', null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'unified_gst_session',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_id'], name='unified_gst_session_04c593_idx'), models.Index(fields=['gstin', 'is_verified'], name='unified_gst_gstin_3064d1_idx')],
            },
        ),
    ]
