# Generated by Django 6.0 on 2026-01-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst_reports', '0002_sandboxaccesstoken_cachedgstresponse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gstreport',
            name='report_type',
            field=models.CharField(choices=[('GSTR1_VS_3B', 'GSTR-1 vs GSTR-3B'), ('GSTR1_VS_BOOK', 'GSTR-1 vs Books'), ('GSTR3B_VS_BOOK', 'GSTR-3B vs Books'), ('GSTR2B_VS_BOOK', 'GSTR-2B vs Books'), ('GSTR1_3B_2B_COMPREHENSIVE', 'GSTR-1 vs 3B vs 2B Comprehensive')], db_index=True, max_length=50),
        ),
    ]
