# Generated by Django 6.0.1 on 2026-01-22 09:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst_reports', '0003_alter_gstreport_report_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cachedgstresponse',
            name='cached_gst__gstin_8e8e55_idx',
        ),
        migrations.RemoveIndex(
            model_name='unifiedgstsession',
            name='unified_gst_gstin_3064d1_idx',
        ),
        migrations.AlterUniqueTogether(
            name='cachedgstresponse',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='gstreport',
            name='username',
        ),
        migrations.AddField(
            model_name='cachedgstresponse',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gst_cache', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gstreport',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gst_reports', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unifiedgstsession',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gst_sessions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='cachedgstresponse',
            unique_together={('user', 'gstin', 'return_type', 'section', 'year', 'month')},
        ),
        migrations.AddIndex(
            model_name='cachedgstresponse',
            index=models.Index(fields=['user', 'gstin', 'return_type', 'year', 'month'], name='cached_gst__user_id_3db56b_idx'),
        ),
        migrations.AddIndex(
            model_name='unifiedgstsession',
            index=models.Index(fields=['user', 'gstin', 'is_verified'], name='unified_gst_user_id_a1633e_idx'),
        ),
        migrations.RemoveField(
            model_name='unifiedgstsession',
            name='username',
        ),
    ]
