# Generated by Django 6.0.1 on 2026-01-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst_reports', '0004_remove_cachedgstresponse_cached_gst__gstin_8e8e55_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiedgstsession',
            name='gst_username',
            field=models.CharField(blank=True, help_text='Username for GST Portal', max_length=255, null=True),
        ),
    ]
