# Generated by Django 6.0.1 on 2026-01-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst_reports', '0005_unifiedgstsession_gst_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='gstreport',
            name='gst_username',
            field=models.CharField(blank=True, help_text='GST Portal Username', max_length=255, null=True),
        ),
    ]
