# Generated by Django 6.0.1 on 2026-02-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_vault', '0004_folder_document_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
