# Generated by Django 6.0.1 on 2026-02-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_vault', '0005_document_file_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedreport',
            name='is_read',
            field=models.BooleanField(default=False, help_text='Set to True once the client has viewed the report'),
        ),
    ]
