# Generated by Django 6.0.1 on 2026-03-30 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_vault', '0008_documentdownloadlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='documentdownloadlog',
            new_name='vault_docum_documen_4a25fd_idx',
            old_name='vault_docum_documen_910da8_idx',
        ),
        migrations.RenameIndex(
            model_name='documentdownloadlog',
            new_name='vault_docum_consult_b60c77_idx',
            old_name='vault_docum_consult_7836ae_idx',
        ),
    ]
