# Generated by Django 6.0.1 on 2026-03-05 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatorSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculator_type', models.CharField(max_length=50)),
                ('data', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculator_saves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'calculator_type')},
            },
        ),
    ]
