# Generated by Django 6.0.1 on 2026-02-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('document', 'Document'), ('service', 'Service'), ('meeting', 'Meeting'), ('consultation', 'Consultation'), ('chat', 'Chat'), ('payment', 'Payment'), ('system', 'System')], default='system', max_length=20),
        ),
    ]
